<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Location\Entities\District;

class LocationSeeder extends Seeder
{
    
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        $locations = [
            ['name'=>'Dhaka', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Faridpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gazipur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gopalganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Jamalpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kishoreganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Madaripur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Manikganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Munshiganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Mymensingh', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Narayanganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Narsingdi', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Netrokona', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Rajbari', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Shariatpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sherpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Tangail', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Bogra', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Joypurhat', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Naogaon', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Natore', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Nawabganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Pabna', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Rajshahi', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sirajgonj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Dinajpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gaibandha', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kurigram', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Lalmonirhat', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Nilphamari', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Panchagarh', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Rangpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Thakurgaon', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Barguna', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Barisal', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Bhola', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Jhalokati', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Patuakhali', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Pirojpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Bandarban', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Brahmanbaria', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Chandpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Chittagong', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Comilla', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Cox\'s Bazar', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Feni', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Khagrachari', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Lakshmipur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Noakhali', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Rangamati', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Habiganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Maulvibazar', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sunamganj', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sylhet', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Bagerhat', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Chuadanga', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Jessore', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Jhenaidah', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Khulna', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kushtia', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Magura', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Meherpur', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Narail', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Satkhira', 'parent_id'=>0,'type'=>1,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gulsan 1', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Dhamrai Upazila', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Dohar Upazila', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Keraniganj Upazila', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Nawabganj Upazila', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Savar Upazila', 'parent_id'=>1,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Charbhadrasan Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sadarpur Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Shaltha Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Nagarkanda Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Bhanga Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Madhukhali Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Alfadanga Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Boalmari Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Faridpur Sadar Upazila', 'parent_id'=>2,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Tongi', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kaliganj', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sripur', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kapasia', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kaliakior', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gazipur Sadar-Joydebpur', 'parent_id'=>3,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kotalipara Upazila', 'parent_id'=>4,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Tungipara Upazila', 'parent_id'=>4,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Muksudpur Upazila', 'parent_id'=>4,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Kashiani Upazila', 'parent_id'=>4,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Gopalganj Sadar Upazila', 'parent_id'=>4,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Sarishabari Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Melandaha Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Narundi Police I.C', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Madarganj Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Jamalpur Sadar Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Islampur Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Baksiganj Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Dewanganj Upazila', 'parent_id'=>5,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=>'Tarail Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pakundia Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nikli Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mithamain Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kuliarchar Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kishoreganj Sadar Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Karimganj Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Itna Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Astagram Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bajitpur Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hossainpur Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhairab Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Katiadi Upazila', 'parent_id'=>6,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalkini', 'parent_id'=>7,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajoir', 'parent_id'=>7,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Madaripur Sadar', 'parent_id'=>7,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shibchar', 'parent_id'=>7,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Harirampur Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Manikganj Sadar Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Daulatpur Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ghior Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Singair Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shibalaya Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Saturia Upazila', 'parent_id'=>8,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tongibari Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sirajdikhan Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Munshiganj Sadar Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sreenagar Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gazaria Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lohajang Upazila', 'parent_id'=>9,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nandail', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Phulpur', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mymensingh Sadar', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ishwarganj', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gauripur', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gaffargaon', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fulbaria', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dhobaura', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Trishal', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Haluaghat', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhaluka', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Muktagachha', 'parent_id'=>10,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rupganj Upazila', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Naryanganj Sadar Upazila', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bandar', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sonargaon Upazila', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Araihazar Upazila', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Siddirgonj Upazila', 'parent_id'=>11,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shibpur Upazila', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Raipura Upazila, Narsingdi', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Palash Upazila', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Narsingdi Sadar Upazila', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Monohardi Upazila', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Belabo Upazila', 'parent_id'=>12,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khaliajuri Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Purbadhala Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Netrakona-S Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mohanganj Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Madan Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalmakanda Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Durgapur Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barhatta Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Atpara Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kendua Upazilla', 'parent_id'=>13,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajbari Sadar Upazila', 'parent_id'=>14,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalukhali Upazila', 'parent_id'=>14,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pangsha Upazila', 'parent_id'=>14,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Goalandaghat Upazila', 'parent_id'=>14,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Baliakandi Upazila', 'parent_id'=>14,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gosairhat Upazila', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhedarganj Upazila', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jajira Upazila', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Damudya Upazila', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shariatpur Sadar -Palong', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Naria Upazila', 'parent_id'=>15,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sreebardi Upazila', 'parent_id'=>16,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sherpur Sadar Upazila', 'parent_id'=>16,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nalitabari Upazila', 'parent_id'=>16,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nakla Upazila', 'parent_id'=>16,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jhenaigati Upazila', 'parent_id'=>16,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tangail Sadar Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sakhipur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Basail Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Madhupur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ghatail Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalihati Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dhanbari Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhuapur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Delduar Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gopalpur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mirzapur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nagarpur Upazila', 'parent_id'=>17,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sonatala', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shibganj', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sariakandi', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sahajanpur', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nandigram', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kahaloo', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Adamdighi', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gabtali', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dhupchanchia', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dhunat', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bogra Sadar', 'parent_id'=>18,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Panchbibi', 'parent_id'=>19,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khetlal', 'parent_id'=>19,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalai', 'parent_id'=>19,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Joypurhat S', 'parent_id'=>19,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Akkelpur', 'parent_id'=>19,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Patnitala Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dhamoirhat Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sapahar Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Porsha Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Badalgachhi Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Atrai Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Niamatpur Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Raninagar Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Manda Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mohadevpur Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Naogaon Sadar Upazila', 'parent_id'=>20,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Baraigram Upazila', 'parent_id'=>21,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Natore Sadar Upazila', 'parent_id'=>21,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lalpur Upazila', 'parent_id'=>21,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagatipara Upazila', 'parent_id'=>21,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shibganj Upazila', 'parent_id'=>22,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nawabganj Sadar Upazila', 'parent_id'=>22,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nachole Upazila', 'parent_id'=>22,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gomastapur Upazila', 'parent_id'=>22,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bholahat Upazila', 'parent_id'=>22,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sujanagar Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Santhia Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pabna Sadar Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ishwardi Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Faridpur Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chatmohar Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhangura Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bera Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Atgharia Upazila', 'parent_id'=>23,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Godagari', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tanore', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Puthia', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Paba', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mohanpur', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Durgapur', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Charghat', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagmara', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagha', 'parent_id'=>24,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chauhali Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ullahpara Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tarash Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shahjadpur Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Raiganj Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kazipur Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kamarkhanda Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Belkuchi Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sirajganj Sadar Upazila', 'parent_id'=>25,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hakimpur Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaharole Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khansama Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dinajpur Sadar Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nawabganj', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Parbatipur Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ghoraghat Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Phulbari Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chirirbandar Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bochaganj Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Biral Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Birganj', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Birampur Upazila', 'parent_id'=>26,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sadullapur', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Saghata', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sundarganj', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Palashbari', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gaibandha sadar', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fulchhari', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gobindaganj', 'parent_id'=>27,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Char Rajibpur', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rowmari', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chilmari', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ulipur', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajarhat', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Phulbari', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhurungamari', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nageshwari', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kurigram Sadar', 'parent_id'=>28,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Patgram', 'parent_id'=>29,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hatibandha', 'parent_id'=>29,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaliganj', 'parent_id'=>29,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Aditmari', 'parent_id'=>29,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lalmanirhat Sadar', 'parent_id'=>29,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dimla', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Domar', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kishoreganj', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jaldhaka', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Saidpur', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nilphamari Sadar', 'parent_id'=>30,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Panchagarh Sadar', 'parent_id'=>31,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Debiganj', 'parent_id'=>31,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Boda', 'parent_id'=>31,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Atwari', 'parent_id'=>31,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tetulia', 'parent_id'=>31,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaunia', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Badarganj', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mithapukur', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gangachara', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rangpur Sadar', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pirgachha', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pirganj', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Taraganj', 'parent_id'=>32,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Baliadangi Upazila', 'parent_id'=>33,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Thakurgaon Sadar Upazila', 'parent_id'=>33,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pirganj Upazila', 'parent_id'=>33,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Haripur Upazila', 'parent_id'=>33,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ranisankail Upazila', 'parent_id'=>33,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Patharghata Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Betagi Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barguna Sadar Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bamna Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Taltali Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Amtali Upazila', 'parent_id'=>34,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gaurnadi Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Banaripara Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hizla Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mehendiganj Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Wazirpur Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bakerganj Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barisal Sadar Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Babuganj Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Muladi Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Agailjhara Upazila', 'parent_id'=>35,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Daulatkhan Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tazumuddin Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Manpura Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lalmohan Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Char Fasson Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Burhanuddin Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhola Sadar Upazila', 'parent_id'=>36,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nalchity Upazila', 'parent_id'=>37,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajapur Upazila', 'parent_id'=>37,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jhalokati Sadar Upazila', 'parent_id'=>37,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kathalia Upazila', 'parent_id'=>37,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mirzaganj Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Patuakhali Sadar Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rangabali Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dumki Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalapara Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Galachipa Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dashmina Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bauphal Upazila', 'parent_id'=>38,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Zianagar', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pirojpur Sadar', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nazirpur', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mathbaria', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaukhali', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bhandaria', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nesarabad', 'parent_id'=>39,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rowangchhari', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ruma', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ali kadam', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Naikhongchhari', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lama', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Thanchi', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bandarban Sadar', 'parent_id'=>40,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bancharampur Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bijoynagar Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ashuganj Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Akhaura Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kasba Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shahbazpur Town', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sarail Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nabinagar Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nasirnagar Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Brahmanbaria Sadar Upazila', 'parent_id'=>41,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shahrasti', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Matlab Dakkhin', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Matlab Uttar', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kachua', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Haziganj', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Faridganj', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chandpur Sadar', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Haimchar', 'parent_id'=>42,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Patiya Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rangunia Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Raozan Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sandwip Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Satkania Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sitakunda Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mirsharai Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lohagara Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hathazari Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fatikchhari Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chandanaish Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khulshi', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Banshkhali Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Anwara Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Panchlaish', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Boalkhali Upazila', 'parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chittagong Port','parent_id'=>43,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chauddagram Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Monohorgonj Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Laksam Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Comilla Sadar Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Homna Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Debidwar Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Daudkandi Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chandina Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Burichong Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Brahmanpara Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barura Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Meghna Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nangalkot Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Comilla Sadar South Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Titas Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Muradnagar Upazila', 'parent_id'=>44,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kutubdia Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Pekua Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ukhia Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Teknaf Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ramu Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Maheshkhali Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Cox\'s Bazar Sadar Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chakaria Upazila', 'parent_id'=>45,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sonagazi', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fhulgazi', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Parshuram', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chagalnaiya', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Feni Sadar', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Daganbhyan', 'parent_id'=>46,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dighinala Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ramgarh Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Panchhari Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Matiranga Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mahalchhari Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lakshmichhari Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khagrachhari Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Manikchhari Upazila', 'parent_id'=>47,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lakshmipur Sadar Upazila', 'parent_id'=>48,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Komol Nagar Upazila', 'parent_id'=>48,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ramgati Upazila', 'parent_id'=>48,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Raipur Upazila', 'parent_id'=>48,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ramganj Upazila', 'parent_id'=>48,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chatkhil Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Begumganj Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Noakhali Sadar Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shenbag Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Hatia Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kobirhat Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sonaimuri Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Suborno Char Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Companyganj Upazila', 'parent_id'=>49,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagaichhari Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaptai Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Langadu Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nannerchar Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaukhali Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajasthali Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Juraichhari Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barkal Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rangamati Sadar Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Belaichhari Upazila', 'parent_id'=>50,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nabiganj', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Madhabpur', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lakhai', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Habiganj Sadar', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chunarughat', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shaistagonj Upazila', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bahubal', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Ajmiriganj', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Baniachang', 'parent_id'=>51,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sreemangal', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rajnagar', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kulaura', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kamalganj', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Barlekha', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Moulvibazar Sadar', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Juri', 'parent_id'=>52,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sulla', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jamalganj', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tahirpur', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jagannathpur', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dowarabazar', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dharampasha', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Derai', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chhatak', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bishwamvarpur', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shanthiganj', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sunamganj Sadar', 'parent_id'=>53,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sylhet Sadar', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Beanibazar', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bishwanath', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Balaganj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Companiganj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Golapganj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Gowainghat', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jaintiapur', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kanaighat', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fenchuganj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Zakiganj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Nobigonj', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dakshin Surma Upazila', 'parent_id'=>54,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chitalmari Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagerhat Sadar Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Fakirhat Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kachua Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mollahat Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mongla Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Morrelganj Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rampal Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sarankhola Upazila', 'parent_id'=>55,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chuadanga-S Upazila', 'parent_id'=>56,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jibannagar Upazila', 'parent_id'=>56,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Alamdanga Upazila', 'parent_id'=>56,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Damurhuda Upazila', 'parent_id'=>56,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Manirampur Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sharsha Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jhikargachha Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Chaugachha Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Abhaynagar Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jessore Sadar Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bagherpara Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Keshabpur Upazila', 'parent_id'=>57,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Harinakunda Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shailkupa Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kotchandpur Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaliganj Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Maheshpur Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Jhenaidah Sadar Upazila', 'parent_id'=>58,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Batiaghata Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dacope Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dumuria Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Dighalia Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Koyra Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Paikgachha Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Rupsa Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Phultala Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Terokhada Upazila', 'parent_id'=>59,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mirpur', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Daulatpur', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Bheramara', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Khoksa', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kumarkhali', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kushtia Sadar', 'parent_id'=>60,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Sreepur Upazila', 'parent_id'=>61,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Magura Sadar Upazila', 'parent_id'=>61,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mohammadpur Upazila', 'parent_id'=>61,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shalikha Upazila', 'parent_id'=>61,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Meherpur-S Upazila', 'parent_id'=>62,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'angni Upazila', 'parent_id'=>62,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Mujib Nagar Upazila', 'parent_id'=>62,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalia Upazilla', 'parent_id'=>63,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Narail-S Upazilla', 'parent_id'=>63,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Lohagara Upazilla', 'parent_id'=>63,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Shyamnagar Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kaliganj Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Kalaroa Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Tala Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Debhata Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Satkhira Sadar Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
            ['name'=> 'Assasuni Upazila', 'parent_id'=>64,'type'=>2,'created_by' => 'Super Admin','created_at' => date('Y-m-d H:i:s')],
        ];
        District::insert($locations);
    }

}
